var results =
[
  {
    "id": 18,
    "manuscript": "Cāmadevivaṃsa",
    "terminus_post_quem": "1410",
    "terminus_ante_quem": "1410",
    "number_of_folios": null,
    "dimension_width": null,
    "dimension_height": null,
    "script": "Tai Tham",
    "content": "Literary (Chronicle)",
    "religious_affiliation": "Buddhist",
    "current_location": "Lamphun, Thailand",
    "shelfmark": null,
    "findspot": "Lamphun, Thailand",
    "place_of_composition": null,
    "bibliography": "George Cœdès, \"Documents sur l'histoire politique et religieuse du Laos occidental,\" in Bulletin de l'École française d'Extrême-Orient 25 (1925): 1-201.",
    "scientific_analysis": null,
    "bilingual": null,
    "palimpsest": null,
    "colophon": null,
    "latitude": "18.25",
    "longitude": "98.9167",
    "printing": null,
    "entry_researcher": "Paul Dilley",
    "second_language": null,
    "second_script": null,
    "bilingual_format": null,
    "upper_text_language": null,
    "upper_text_script": null,
    "upper_text_content": null,
    "scribe": null,
    "patron": null,
    "text_of_colophon": null,
    "geopolitical_context": "Lanna Kingdom Thailand",
    "languages": [
      "Pali"
    ],
    "forms": [
      "Pothi"
    ],
    "materials": [
      "Palm Leaf"
    ]
  },
  {
    "id": 26,
    "manuscript": "Vienna Genesis",
    "terminus_post_quem": "500",
    "terminus_ante_quem": "550",
    "number_of_folios": 24,
    "dimension_width": "26.5",
    "dimension_height": "32.6",
    "script": "Uncial",
    "content": "Religious (Old Testament)",
    "religious_affiliation": "Christian",
    "current_location": "Österreichische Nationalbibliothek, Vienna",
    "shelfmark": "cod. theol. gr. 31",
    "findspot": null,
    "place_of_composition": "Antioch (default)",
    "bibliography": "Zimmermann, Barbara. Die Wiener Genesis im Rahmen der antiken Buchmalerei. Ikonographie, Darstellung, Illustrationsverfahren und Aussageintention (Wiesbaden: Reichert, 2003).",
    "scientific_analysis": null,
    "bilingual": "N",
    "palimpsest": "N",
    "colophon": "N",
    "latitude": "36.2225515",
    "longitude": "36.183214",
    "printing": null,
    "entry_researcher": "Daphne Becker; Paul Dilley",
    "second_language": null,
    "second_script": null,
    "bilingual_format": null,
    "upper_text_language": null,
    "upper_text_script": null,
    "upper_text_content": null,
    "scribe": null,
    "patron": null,
    "text_of_colophon": null,
    "geopolitical_context": "Roman Levant",
    "languages": [
      "Greek"
    ],
    "forms": [
      "Codex"
    ],
    "materials": [
      "Parchment"
    ]
  },
  {
    "id": 29,
    "manuscript": "Liber Linteus Zagrebensis",
    "terminus_post_quem": "-200",
    "terminus_ante_quem": "-150",
    "number_of_folios": 12,
    "dimension_width": null,
    "dimension_height": null,
    "script": "Old Italic/Etruscan",
    "content": "Religious (Ritual Text)",
    "religious_affiliation": "Polytheist",
    "current_location": "Archaeological Museum, Zagreb",
    "shelfmark": null,
    "findspot": "Alexandria",
    "place_of_composition": "Tuscany (defaulted to Perugia)",
    "bibliography": "L. B. van der Meer, Liber linteus zagrabiensis. The Linen Book of Zagreb. A Comment on the Longest Etruscan Text (Louvain, 2007)",
    "scientific_analysis": null,
    "bilingual": null,
    "palimpsest": null,
    "colophon": null,
    "latitude": "43.111192",
    "longitude": "12.3899085",
    "printing": null,
    "entry_researcher": "Paul Dilley",
    "second_language": null,
    "second_script": null,
    "bilingual_format": null,
    "upper_text_language": null,
    "upper_text_script": null,
    "upper_text_content": null,
    "scribe": null,
    "patron": null,
    "text_of_colophon": null,
    "geopolitical_context": "Roman Republican Italy",
    "languages": [
      "Etruscan"
    ],
    "forms": [
      "Booklet"
    ],
    "materials": [
      "Linen"
    ]
  },
  {
    "id": 30,
    "manuscript": "Senatus Consultum de Bacchanalibus",
    "terminus_post_quem": "-186",
    "terminus_ante_quem": "-186",
    "number_of_folios": null,
    "dimension_width": null,
    "dimension_height": null,
    "script": "Latin",
    "content": "Political",
    "religious_affiliation": "Polytheist",
    "current_location": "Kunsthistorisches Museum, Vienna",
    "shelfmark": "",
    "findspot": "Teura (Tiriolo, Calabria)",
    "place_of_composition": "Teura (Tiriolo, Calabria)",
    "bibliography": "Alfred Ernout, Recueil de Textes Latins Archaiques (Paris: Librairie C. Klincksieck, 1947), 58–68.",
    "scientific_analysis": null,
    "bilingual": null,
    "palimpsest": null,
    "colophon": null,
    "latitude": "38.949346",
    "longitude": "16.510228",
    "printing": null,
    "entry_researcher": "Paul Dilley",
    "second_language": null,
    "second_script": null,
    "bilingual_format": null,
    "upper_text_language": null,
    "upper_text_script": null,
    "upper_text_content": null,
    "scribe": null,
    "patron": null,
    "text_of_colophon": null,
    "geopolitical_context": "Roman Republican Italy",
    "languages": [
      "Latin"
    ],
    "forms": [
      "Inscription"
    ],
    "materials": [
      "Bronze"
    ]
  },
  {
    "id": 31,
    "manuscript": "Iguvine Tablets (7)",
    "terminus_post_quem": "-300",
    "terminus_ante_quem": "0",
    "number_of_folios": null,
    "dimension_width": null,
    "dimension_height": null,
    "script": "Old Italic/Umbrian; Latin",
    "content": "Religious (Ritual Text: Attidian Brethren)",
    "religious_affiliation": "Polytheist",
    "current_location": "Palazzo dei Consoli, Gubbio",
    "shelfmark": null,
    "findspot": "Iguvium",
    "place_of_composition": "Iguvium",
    "bibliography": "Augusto Ancillotti and Romolo Cerri, Le Tavole iguvine: fotografie a colori, facsimili, testo traslitterato, traduzione e commento (Perugia, 1997)",
    "scientific_analysis": null,
    "bilingual": null,
    "palimpsest": null,
    "colophon": null,
    "latitude": "43.355464",
    "longitude": "12.573438",
    "printing": null,
    "entry_researcher": "Paul Dilley",
    "second_language": null,
    "second_script": null,
    "bilingual_format": null,
    "upper_text_language": null,
    "upper_text_script": null,
    "upper_text_content": null,
    "scribe": null,
    "patron": null,
    "text_of_colophon": null,
    "geopolitical_context": "Roman Republican Italy",
    "languages": [
      "Umbrian"
    ],
    "forms": [
      "Inscription"
    ],
    "materials": [
      "Bronze"
    ]
  },
  {
    "id": 25,
    "manuscript": "Birmingham Quran ",
    "terminus_post_quem": "568",
    "terminus_ante_quem": "645",
    "number_of_folios": 2,
    "dimension_width": "25.8",
    "dimension_height": "34.3",
    "script": "Hijazi",
    "content": "Religious (Quran)",
    "religious_affiliation": "Islamic",
    "current_location": "Cadbury Research Library, University of Birmingham",
    "shelfmark": "Mingana 1572a",
    "findspot": null,
    "place_of_composition": "Damascus [default]",
    "bibliography": "A. Fedeli, The Provenance of the Manuscript Mingana Islamic Arabic 1572: Dispersed folios from a few Qur'anic quires' in Manuscripta Orientalia, Vol 17, No 1, June 2011 pp.45-56; <a href=\"https://www.birmingham.ac.uk/facilities/cadbury/TheBirminghamQuranManuscript.aspx\" target=\"_blank\">https://www.birmingham.ac.uk/facilities/cadbury/TheBirminghamQuranManuscript.aspx</a>; <a href=\"https://www.flickr.com/photos/cadburyresearchlibrary/sets/72157655161018888\" target=\"_blank\">https://www.flickr.com/photos/cadburyresearchlibrary/sets/72157655161018888</a>",
    "scientific_analysis": "Radiocarbon Dating",
    "bilingual": "N",
    "palimpsest": "N",
    "colophon": "N",
    "latitude": "33.511612",
    "longitude": "36.309102",
    "printing": null,
    "entry_researcher": "Maya Amjadi, Paul Dilley",
    "second_language": null,
    "second_script": null,
    "bilingual_format": null,
    "upper_text_language": null,
    "upper_text_script": null,
    "upper_text_content": null,
    "scribe": null,
    "patron": null,
    "text_of_colophon": null,
    "geopolitical_context": "Rashidun/Umayyad Levant",
    "languages": [
      "Arabic"
    ],
    "forms": [
      "Codex"
    ],
    "materials": [
      "Parchment"
    ]
  },
  {
    "id": 28,
    "manuscript": "Codex Ephraemi Rescriptus",
    "terminus_post_quem": "400",
    "terminus_ante_quem": "500",
    "number_of_folios": 208,
    "dimension_width": "27",
    "dimension_height": "33",
    "script": "Uncial",
    "content": "Religious (New Testament)",
    "religious_affiliation": "Christian",
    "current_location": "Bibliothèque Nationale de France, Paris",
    "shelfmark": "Grec 9",
    "findspot": null,
    "place_of_composition": "Alexandria (default)",
    "bibliography": "Constantin Tischendorf, Codex Ephraemi Syri Rescriptus sive Fragmenta Novi Testamenti (Leipsic, 1843)",
    "scientific_analysis": null,
    "bilingual": "N",
    "palimpsest": "Y",
    "colophon": "N",
    "latitude": "31.201435",
    "longitude": "29.909773",
    "printing": null,
    "entry_researcher": "Anne Fish",
    "second_language": null,
    "second_script": null,
    "bilingual_format": null,
    "upper_text_language": null,
    "upper_text_script": null,
    "upper_text_content": null,
    "scribe": null,
    "patron": null,
    "text_of_colophon": null,
    "geopolitical_context": "Roman Egypt and Nubia",
    "languages": [
      "Greek"
    ],
    "forms": [
      "Codex"
    ],
    "materials": [
      "Parchment"
    ]
  },
  {
    "id": 24,
    "manuscript": "Book of Armagh",
    "terminus_post_quem": "807",
    "terminus_ante_quem": "807",
    "number_of_folios": 221,
    "dimension_width": "14.6",
    "dimension_height": "19.7",
    "script": "Insular Miniscule",
    "content": "Religious (New Testament, Selections; Texts on St. Patrick)",
    "religious_affiliation": "Christian",
    "current_location": "Trinity College Dublin",
    "shelfmark": "52",
    "findspot": null,
    "place_of_composition": "Armagh",
    "bibliography": "John Gwynn, Liber Ardmachanus: The Book of Armagh (Dublin, 1913); \n<a href=\"http://confessio.ie/manuscripts/dublin#1\" target=\"_blank\">http://confessio.ie/manuscripts/dublin#1</a>",
    "scientific_analysis": null,
    "bilingual": "Y",
    "palimpsest": null,
    "colophon": "Y",
    "latitude": "54.3503",
    "longitude": "-6.6528",
    "printing": null,
    "entry_researcher": "Paul Dilley",
    "second_language": "Old Irish",
    "second_script": "Insular Miniscule",
    "bilingual_format": "Separate Texts",
    "upper_text_language": null,
    "upper_text_script": null,
    "upper_text_content": null,
    "scribe": "Ferdomnach",
    "patron": "Abbot Torbach of Armagh",
    "text_of_colophon": null,
    "geopolitical_context": "Early Christian Ireland",
    "languages": [
      "Old Irish",
      "Latin"
    ],
    "forms": [
      "Codex"
    ],
    "materials": [
      "Parchment"
    ]
  },
  {
    "id": 17,
    "manuscript": "Guodian Chu Slips",
    "terminus_post_quem": "-400",
    "terminus_ante_quem": "-300",
    "number_of_folios": null,
    "dimension_width": null,
    "dimension_height": null,
    "script": "Chinese",
    "content": null,
    "religious_affiliation": "Daoist, Confucian",
    "current_location": null,
    "shelfmark": null,
    "findspot": "Guodian",
    "place_of_composition": "Jingmen, Hubei",
    "bibliography": "Kenneth Holloway, Guodian: The Newly Discovered Seeds of Chinese Religious and Political Philosophy (Oxford, 2009)",
    "scientific_analysis": null,
    "bilingual": null,
    "palimpsest": null,
    "colophon": null,
    "latitude": "31.1124",
    "longitude": "112.6431",
    "printing": null,
    "entry_researcher": "Paul Dilley",
    "second_language": null,
    "second_script": null,
    "bilingual_format": null,
    "upper_text_language": null,
    "upper_text_script": null,
    "upper_text_content": null,
    "scribe": null,
    "patron": null,
    "text_of_colophon": null,
    "geopolitical_context": "Warring States China",
    "languages": [
      "Chinese"
    ],
    "forms": [
      "Slips"
    ],
    "materials": [
      "Bamboo"
    ]
  },
  {
    "id": 21,
    "manuscript": "Minoan Tablet",
    "terminus_post_quem": "-1800",
    "terminus_ante_quem": "-1450",
    "number_of_folios": 1,
    "dimension_width": null,
    "dimension_height": null,
    "script": "Linear A",
    "content": "Undeciphered",
    "religious_affiliation": null,
    "current_location": "Archaeological Museum of Sitia",
    "shelfmark": null,
    "findspot": "Palace of Zakros, Crete",
    "place_of_composition": "Palace of Zakros, Crete",
    "bibliography": "John Marangozis, An introduction to Minoan Linear A (Munich, 2007)",
    "scientific_analysis": null,
    "bilingual": null,
    "palimpsest": null,
    "colophon": null,
    "latitude": "35.0980695",
    "longitude": "26.26125",
    "printing": null,
    "entry_researcher": "Paul Dilley",
    "second_language": null,
    "second_script": null,
    "bilingual_format": null,
    "upper_text_language": null,
    "upper_text_script": null,
    "upper_text_content": null,
    "scribe": null,
    "patron": null,
    "text_of_colophon": null,
    "geopolitical_context": "Minoan Greece",
    "languages": [
      "Minoan"
    ],
    "forms": [
      "Tablet"
    ],
    "materials": [
      "Clay"
    ]
  },
  {
    "id": 23,
    "manuscript": "Phaistos Disc",
    "terminus_post_quem": "-2000",
    "terminus_ante_quem": "-1000",
    "number_of_folios": 1,
    "dimension_width": null,
    "dimension_height": null,
    "script": "Cretan Hieroglyphic",
    "content": "Undeciphered",
    "religious_affiliation": null,
    "current_location": "Heraklion Archaeological Museum",
    "shelfmark": null,
    "findspot": "Phaistos (Minoan Palace)",
    "place_of_composition": "Phaistos, Crete",
    "bibliography": "Louis Godart, The Phaistos Disc: The Enigma of an Aegean Script (Heraklion, 1995); 15cm diameter.",
    "scientific_analysis": null,
    "bilingual": null,
    "palimpsest": null,
    "colophon": null,
    "latitude": "35.0511785",
    "longitude": "24.8141725",
    "printing": null,
    "entry_researcher": "Paul Dilley",
    "second_language": null,
    "second_script": null,
    "bilingual_format": null,
    "upper_text_language": null,
    "upper_text_script": null,
    "upper_text_content": null,
    "scribe": null,
    "patron": null,
    "text_of_colophon": null,
    "geopolitical_context": "Minoan Greece",
    "languages": [
      "Minoan"
    ],
    "forms": [
      "Disc-15cm"
    ],
    "materials": [
      "Clay"
    ]
  },
  {
    "id": 27,
    "manuscript": "Topkapi Quran",
    "terminus_post_quem": "750",
    "terminus_ante_quem": "850",
    "number_of_folios": 408,
    "dimension_width": "41",
    "dimension_height": "46",
    "script": "Kufic",
    "content": "Religious (Quran)",
    "religious_affiliation": "Islamic",
    "current_location": "Topkapi Palace Museum, Istanbul",
    "shelfmark": null,
    "findspot": null,
    "place_of_composition": "Damascus (default)",
    "bibliography": "T. Altikulaç, Al-Muṣḥaf Al-Sharif: Attributed To ʿUthmān Bin ʿAffān (The Copy At The Topkapi Palace Museum), 2007, Organization of the Islamic Conference Research Centre for Islamic History, Art and Culture: Istanbul; Images at:\n<a href=\"https://www.islamic-awareness.org/quran/text/mss/topkapi\" target=\"_blank\">https://www.islamic-awareness.org/quran/text/mss/topkapi</a>",
    "scientific_analysis": null,
    "bilingual": "N",
    "palimpsest": "N",
    "colophon": "N",
    "latitude": "33.511612",
    "longitude": "36.309102",
    "printing": null,
    "entry_researcher": "Mohamad Bin Mohdhasli",
    "second_language": null,
    "second_script": null,
    "bilingual_format": null,
    "upper_text_language": null,
    "upper_text_script": null,
    "upper_text_content": null,
    "scribe": null,
    "patron": null,
    "text_of_colophon": null,
    "geopolitical_context": "Rashidun/Umayyad Levant",
    "languages": [
      "Arabic"
    ],
    "forms": [
      "Codex"
    ],
    "materials": [
      "Parchment"
    ]
  },
  {
    "id": 19,
    "manuscript": "Pyrgi Tablets (Etruscan)",
    "terminus_post_quem": "-509",
    "terminus_ante_quem": "-509",
    "number_of_folios": 1,
    "dimension_width": "8.7",
    "dimension_height": "18.5",
    "script": "Etruscan",
    "content": "Religious (Ritual Text)",
    "religious_affiliation": "Polytheist",
    "current_location": "Museo Nazionale di Villa Giulia, Rome",
    "shelfmark": null,
    "findspot": "Pyrgi",
    "place_of_composition": "Pyrgi",
    "bibliography": "D.F. Maras, Il dono votivo. Gli dei e il sacro nelle iscrizioni etrusche di culto (Pisa/Rome, 2009) ",
    "scientific_analysis": null,
    "bilingual": "N",
    "palimpsest": "N",
    "colophon": "N",
    "latitude": "42.015753055",
    "longitude": "11.9617070622",
    "printing": null,
    "entry_researcher": "Paul Dilley",
    "second_language": null,
    "second_script": null,
    "bilingual_format": null,
    "upper_text_language": null,
    "upper_text_script": null,
    "upper_text_content": null,
    "scribe": null,
    "patron": null,
    "text_of_colophon": null,
    "geopolitical_context": "Etruscan Italy",
    "languages": [
      "Etruscan"
    ],
    "forms": [
      "Tablet"
    ],
    "materials": [
      "Gold"
    ]
  },
  {
    "id": 20,
    "manuscript": "Pyrgi Tablet (Phoenician)",
    "terminus_post_quem": "-509",
    "terminus_ante_quem": "-509",
    "number_of_folios": 1,
    "dimension_width": "8.7",
    "dimension_height": "19.3",
    "script": "Phoenician",
    "content": "Religious (Ritual Text)",
    "religious_affiliation": "Polytheist",
    "current_location": "Museo Nazionale di Villa Giulia, Rome",
    "shelfmark": null,
    "findspot": "Pyrgi",
    "place_of_composition": "Pyrgi",
    "bibliography": "Philip Schmitz, \"The Phoenician Text from the Etruscan Sanctuary at Pyrgi,\" Journal of the American Oriental Society 115 (1995):559-575.",
    "scientific_analysis": null,
    "bilingual": null,
    "palimpsest": null,
    "colophon": null,
    "latitude": "42.015753055",
    "longitude": "11.9617070622",
    "printing": null,
    "entry_researcher": "Paul Dilley",
    "second_language": null,
    "second_script": null,
    "bilingual_format": null,
    "upper_text_language": null,
    "upper_text_script": null,
    "upper_text_content": null,
    "scribe": null,
    "patron": null,
    "text_of_colophon": null,
    "geopolitical_context": "Etruscan Italy",
    "languages": [
      "Phoenician"
    ],
    "forms": [
      "Tablet"
    ],
    "materials": [
      "Gold"
    ]
  },
  {
    "id": 22,
    "manuscript": "Tablet from \"Nestor's Palace\"",
    "terminus_post_quem": "-1300",
    "terminus_ante_quem": "-1200",
    "number_of_folios": 1,
    "dimension_width": null,
    "dimension_height": null,
    "script": "Linear B",
    "content": "Documentary (List)",
    "religious_affiliation": null,
    "current_location": "Athens Museum?",
    "shelfmark": null,
    "findspot": "Nestor's Palace, Pylos",
    "place_of_composition": "Pylos",
    "bibliography": "J.T. Hooker, Linear B: An Introduction (Bristol, 1991); image at <a href=\"https://www.brown.edu/Departments/Joukowsky_Institute/courses/greekpast/4690.html\" target=\"_blank\">https://www.brown.edu/Departments/Joukowsky_Institute/courses/greekpast/4690.html</a>\n\n",
    "scientific_analysis": null,
    "bilingual": null,
    "palimpsest": null,
    "colophon": null,
    "latitude": "36.9520305",
    "longitude": "21.659888",
    "printing": null,
    "entry_researcher": "Paul Dilley",
    "second_language": null,
    "second_script": null,
    "bilingual_format": null,
    "upper_text_language": null,
    "upper_text_script": null,
    "upper_text_content": null,
    "scribe": null,
    "patron": null,
    "text_of_colophon": null,
    "geopolitical_context": "Mycenaean Greece",
    "languages": [
      "Greek"
    ],
    "forms": [
      "Tablet"
    ],
    "materials": [
      "Clay"
    ]
  },
  {
    "id": 15,
    "manuscript": "Dipylon (Earliest Greek Inscription)",
    "terminus_post_quem": "-800",
    "terminus_ante_quem": "-700",
    "number_of_folios": null,
    "dimension_width": null,
    "dimension_height": null,
    "script": "Greek",
    "content": "Literary (Poetry)",
    "religious_affiliation": null,
    "current_location": null,
    "shelfmark": null,
    "findspot": "Athens",
    "place_of_composition": "Athens",
    "bibliography": "N.M. Binek, \"The Dipylon Oinochoe Graffito: Text or Decoration?\", Hesperia 86 (2017): 423–42.",
    "scientific_analysis": null,
    "bilingual": null,
    "palimpsest": null,
    "colophon": null,
    "latitude": "37.9728191495",
    "longitude": "23.7237438519",
    "printing": null,
    "entry_researcher": "Paul Dilley",
    "second_language": null,
    "second_script": null,
    "bilingual_format": null,
    "upper_text_language": null,
    "upper_text_script": null,
    "upper_text_content": null,
    "scribe": null,
    "patron": null,
    "text_of_colophon": null,
    "geopolitical_context": "Archaic Greece",
    "languages": [
      "Greek"
    ],
    "forms": [
      "Inscription"
    ],
    "materials": [
      "Ceramic"
    ]
  },
  {
    "id": 16,
    "manuscript": "Derveni Papyrus (Earliest European Manuscript)",
    "terminus_post_quem": "-400",
    "terminus_ante_quem": "-300",
    "number_of_folios": null,
    "dimension_width": null,
    "dimension_height": null,
    "script": "Greek",
    "content": "Religious (Poetic Theogony)",
    "religious_affiliation": "Polytheist",
    "current_location": null,
    "shelfmark": null,
    "findspot": "Derveni, Kingdom of Macedonia",
    "place_of_composition": null,
    "bibliography": "Gabor Betegh, The Derveni Papyrus: Cosmology, Theology and Interpretation (Cambridge, 2004)",
    "scientific_analysis": null,
    "bilingual": null,
    "palimpsest": null,
    "colophon": null,
    "latitude": "40.74493",
    "longitude": "22.978076",
    "printing": null,
    "entry_researcher": "Paul Dilley",
    "second_language": null,
    "second_script": null,
    "bilingual_format": null,
    "upper_text_language": null,
    "upper_text_script": null,
    "upper_text_content": null,
    "scribe": null,
    "patron": null,
    "text_of_colophon": null,
    "geopolitical_context": "Classical Greece; Hellenistic Greece",
    "languages": [
      "Greek"
    ],
    "forms": [
      "Scroll"
    ],
    "materials": [
      "Papyrus"
    ]
  },
  {
    "id": 14,
    "manuscript": "Praeneste Fibula (Earliest Latin Inscription)",
    "terminus_post_quem": "-700",
    "terminus_ante_quem": "-600",
    "number_of_folios": null,
    "dimension_width": null,
    "dimension_height": null,
    "script": "Latin",
    "content": "Documentary (Dedication)",
    "religious_affiliation": null,
    "current_location": null,
    "shelfmark": null,
    "findspot": "Praeneste/Palestrina (Bernardini Tomb)",
    "place_of_composition": "Praeneste/Palestrina",
    "bibliography": "Elisabetta Mangani, “La Fibula Prenestina,” in Bullettino di Paletnologia Italiana 99 (2014): 1-39.",
    "scientific_analysis": null,
    "bilingual": null,
    "palimpsest": null,
    "colophon": null,
    "latitude": "41.8394835",
    "longitude": "12.8923075",
    "printing": null,
    "entry_researcher": "Paul Dilley",
    "second_language": null,
    "second_script": null,
    "bilingual_format": null,
    "upper_text_language": null,
    "upper_text_script": null,
    "upper_text_content": null,
    "scribe": null,
    "patron": null,
    "text_of_colophon": null,
    "geopolitical_context": "Roman Kingdom Italy",
    "languages": [
      "Latin"
    ],
    "forms": [
      "Inscription"
    ],
    "materials": [
      "Gold"
    ]
  },
  {
    "id": 13,
    "manuscript": "Khotan Dharmapada/Gandhari Dharmapada",
    "terminus_post_quem": "100",
    "terminus_ante_quem": "200",
    "number_of_folios": null,
    "dimension_width": null,
    "dimension_height": null,
    "script": "Kharosthi",
    "content": "Religious (Dharmapada)",
    "religious_affiliation": "Buddhist",
    "current_location": "Bibliothèque Nationale de France, Paris; Russian Academy of Sciences, Saint Petersburg",
    "shelfmark": null,
    "findspot": "Khotan",
    "place_of_composition": null,
    "bibliography": "John Brough, The Ghandhari Dharmapada (1962)",
    "scientific_analysis": null,
    "bilingual": null,
    "palimpsest": null,
    "colophon": null,
    "latitude": "37.1075",
    "longitude": "79.9355",
    "printing": null,
    "entry_researcher": "Paul Dilley",
    "second_language": null,
    "second_script": null,
    "bilingual_format": null,
    "upper_text_language": null,
    "upper_text_script": null,
    "upper_text_content": null,
    "scribe": null,
    "patron": null,
    "text_of_colophon": null,
    "geopolitical_context": "Kingdom of Khotan Central Asia",
    "languages": [
      "Prakrit"
    ],
    "forms": [
      "Scroll"
    ],
    "materials": [
      "Birchbark"
    ]
  },
  {
    "id": 9,
    "manuscript": "Great Harris Papyrus (Longest surviving ancient Egyptian papyrus)",
    "terminus_post_quem": "-1166",
    "terminus_ante_quem": "-1166",
    "number_of_folios": null,
    "dimension_width": "4100",
    "dimension_height": null,
    "script": "Hieratic",
    "content": "Literary (Historical)",
    "religious_affiliation": "Polytheist",
    "current_location": "British Museum, London",
    "shelfmark": "Papyrus British Museum 9999 (P. Harris 1)",
    "findspot": "Medinet Habu",
    "place_of_composition": null,
    "bibliography": "Pierre Grandet, Le papyrus Harris I (BM 9999). 2 vols. Bibliothèque d'Étude 109/1–2. (Cairo, 1994)",
    "scientific_analysis": null,
    "bilingual": null,
    "palimpsest": null,
    "colophon": null,
    "latitude": "25.7200144111",
    "longitude": "32.5998824787",
    "printing": null,
    "entry_researcher": "Paul Dilley",
    "second_language": null,
    "second_script": null,
    "bilingual_format": null,
    "upper_text_language": null,
    "upper_text_script": null,
    "upper_text_content": null,
    "scribe": null,
    "patron": null,
    "text_of_colophon": null,
    "geopolitical_context": "New Kingdom Egypt and Nubia",
    "languages": [
      "Ancient Egyptian"
    ],
    "forms": [
      "Scroll"
    ],
    "materials": [
      "Papyrus"
    ]
  },
  {
    "id": 11,
    "manuscript": "Bamiyan Manuscripts (ca. 5,000 fragments from ca. 1,000 manuscripts)",
    "terminus_post_quem": "100",
    "terminus_ante_quem": "800",
    "number_of_folios": null,
    "dimension_width": null,
    "dimension_height": null,
    "script": "Brahmi; Kharoṣṭhī",
    "content": "Religious (Buddhist Sutras)",
    "religious_affiliation": "Buddhist",
    "current_location": "Schøyen Collection, Oslo",
    "shelfmark": null,
    "findspot": "Bamiyan",
    "place_of_composition": null,
    "bibliography": "<a href=\"http://www.schoyencollection.com/news-items/bamiyan-buddhist-thailand-exhibition-2010\" target=\"_blank\">http://www.schoyencollection.com/news-items/bamiyan-buddhist-thailand-exhibition-2010</a>\t\t",
    "scientific_analysis": null,
    "bilingual": null,
    "palimpsest": null,
    "colophon": null,
    "latitude": "34.821",
    "longitude": "67.827",
    "printing": null,
    "entry_researcher": "Paul Dilley",
    "second_language": null,
    "second_script": null,
    "bilingual_format": null,
    "upper_text_language": null,
    "upper_text_script": null,
    "upper_text_content": null,
    "scribe": null,
    "patron": null,
    "text_of_colophon": null,
    "geopolitical_context": "Kingdom of Kushan Central Asia",
    "languages": [
      "Prakrit"
    ],
    "forms": [
      "Scrolls"
    ],
    "materials": [
      "Birchbark",
      "Leather",
      "Palm Leaf"
    ]
  },
  {
    "id": 12,
    "manuscript": "Gilgit Manuscripts (approximately 62, not fully catalogued)",
    "terminus_post_quem": "400",
    "terminus_ante_quem": "700",
    "number_of_folios": null,
    "dimension_width": null,
    "dimension_height": null,
    "script": "Brahmi/Sharada",
    "content": "Religious (Lotus Sutra, other Buddhist texts)",
    "religious_affiliation": "Buddhist",
    "current_location": "National Archives, New Delhi; J&K State Government Libraries and Research Department, Jammu and Kashmir",
    "shelfmark": null,
    "findspot": "Gilgit; discovered in a wood box/stupa: http://www.fom.sg/Passage/2014/05manuscripts.pdf ",
    "place_of_composition": null,
    "bibliography": "Oskar Von Hinuber, \"The Gilgit Manuscripts: An Ancient Buddhist Library in Modern Research,\" in Paul Harrison and Jens-Uwe Hartmann, eds., From Birch Bark to Digital Data (Vienna, 2013), 79-136.",
    "scientific_analysis": null,
    "bilingual": null,
    "palimpsest": null,
    "colophon": null,
    "latitude": "35.9187",
    "longitude": "74.3125",
    "printing": null,
    "entry_researcher": "Paul Dilley",
    "second_language": null,
    "second_script": null,
    "bilingual_format": null,
    "upper_text_language": null,
    "upper_text_script": null,
    "upper_text_content": null,
    "scribe": null,
    "patron": null,
    "text_of_colophon": null,
    "geopolitical_context": "Gupta India; ? India",
    "languages": [
      "Hybrid Buddhist Sanskrit"
    ],
    "forms": [
      "Pothi"
    ],
    "materials": [
      "Paper",
      "Birchbark"
    ]
  },
  {
    "id": 10,
    "manuscript": "Gandharan Buddhist Manuscripts",
    "terminus_post_quem": "0",
    "terminus_ante_quem": "150",
    "number_of_folios": null,
    "dimension_width": null,
    "dimension_height": null,
    "script": "Kharoṣṭhī ",
    "content": "Religious (Sutras)",
    "religious_affiliation": "Buddhist",
    "current_location": "British Library, London",
    "shelfmark": null,
    "findspot": "Gandhara (Exact location unknown)",
    "place_of_composition": "Gandhara (Exact location unknown)",
    "bibliography": "Salomon, Richard. Ancient Buddhist Scrolls from Gandhāra (London, 1999); <a href=\"https://gandhari.org/\" target=\"_blank\">https://gandhari.org/</a>",
    "scientific_analysis": null,
    "bilingual": null,
    "palimpsest": null,
    "colophon": null,
    "latitude": "33.74",
    "longitude": "72.8",
    "printing": null,
    "entry_researcher": "Paul Dilley",
    "second_language": null,
    "second_script": null,
    "bilingual_format": null,
    "upper_text_language": null,
    "upper_text_script": null,
    "upper_text_content": null,
    "scribe": null,
    "patron": null,
    "text_of_colophon": null,
    "geopolitical_context": "Kingdom of Kushan Central Asia",
    "languages": [
      "Prakrit"
    ],
    "forms": [
      "Scroll"
    ],
    "materials": [
      "Birchbark"
    ]
  },
  {
    "id": 3,
    "manuscript": "Irk Bitig/Book of Omens",
    "terminus_post_quem": "800",
    "terminus_ante_quem": "1000",
    "number_of_folios": 58,
    "dimension_width": "13.1",
    "dimension_height": "8.1",
    "script": "Runic/Orkhon",
    "content": "Religious (Divination)",
    "religious_affiliation": "Polytheist",
    "current_location": "British Library, London",
    "shelfmark": "Or. 8212 / 161",
    "findspot": "Dunhuang",
    "place_of_composition": "Taygüntan Manichaean Monastery",
    "bibliography": "Talat Tekin, Irk Bitig: The Book of Omens (Wiesbaden, 1993)",
    "scientific_analysis": null,
    "bilingual": null,
    "palimpsest": null,
    "colophon": null,
    "latitude": "40.1667",
    "longitude": "94.6833",
    "printing": null,
    "entry_researcher": "Paul Dilley",
    "second_language": null,
    "second_script": null,
    "bilingual_format": null,
    "upper_text_language": null,
    "upper_text_script": null,
    "upper_text_content": null,
    "scribe": null,
    "patron": null,
    "text_of_colophon": null,
    "geopolitical_context": "Ganzou Uyghur Kingdom Central Asia",
    "languages": [
      "Old Turkic"
    ],
    "forms": [
      "Book/Folded Leaves"
    ],
    "materials": [
      "Paper"
    ]
  },
  {
    "id": 8,
    "manuscript": "Chinese Paper Scroll of Lotus Sutra",
    "terminus_post_quem": "618",
    "terminus_ante_quem": "906",
    "number_of_folios": null,
    "dimension_width": "140",
    "dimension_height": "25.5",
    "script": "Chinese",
    "content": "Religious (Lotus Sutra, chapter 25)",
    "religious_affiliation": "Buddhist",
    "current_location": "British Library, London",
    "shelfmark": "Or.8210/S.217",
    "findspot": "Dunhuang",
    "place_of_composition": null,
    "bibliography": "<a href=\"http://idp.bl.uk:80/database/oo_loader.a4d?pm=Or.8210/S.217;img=1\" target=\"_blank\">http://idp.bl.uk:80/database/oo_loader.a4d?pm=Or.8210/S.217;img=1</a>;\nGiles, L, Descriptive Catalogue of the Chinese Manuscripts from Tunhuang in the British Museum. London: British Museum, 1957. ",
    "scientific_analysis": null,
    "bilingual": null,
    "palimpsest": null,
    "colophon": "Y",
    "latitude": "40.1667",
    "longitude": "94.6833",
    "printing": null,
    "entry_researcher": "Paul Dilley",
    "second_language": null,
    "second_script": null,
    "bilingual_format": null,
    "upper_text_language": null,
    "upper_text_script": null,
    "upper_text_content": null,
    "scribe": null,
    "patron": null,
    "text_of_colophon": null,
    "geopolitical_context": "Ganzou Uyghur Kingdom Central Asia",
    "languages": [
      "Chinese"
    ],
    "forms": [
      "Scroll"
    ],
    "materials": [
      "Paper"
    ]
  },
  {
    "id": 7,
    "manuscript": "Old Tibetan Annals",
    "terminus_post_quem": "850",
    "terminus_ante_quem": "1100",
    "number_of_folios": null,
    "dimension_width": "25.8",
    "dimension_height": "36.4",
    "script": "Old Tibetan?",
    "content": "Literary (Annals); Religious (Chinese Buddhist Sutra on reverse)",
    "religious_affiliation": null,
    "current_location": "Bibliothèque nationale de France, British Library",
    "shelfmark": "Pelliot tibétain 1288, IOL Tib J 750",
    "findspot": "Dunhuang",
    "place_of_composition": null,
    "bibliography": "Jacques Bacot, Frederick William Thomas, Gustave Charles Touissant, Documents de Touen-houang relatifs a l'histoire de Tibet (Paris, 1940-1946).",
    "scientific_analysis": null,
    "bilingual": "Y",
    "palimpsest": null,
    "colophon": null,
    "latitude": "40.1421",
    "longitude": "94.662",
    "printing": null,
    "entry_researcher": "Paul Dilley",
    "second_language": null,
    "second_script": null,
    "bilingual_format": null,
    "upper_text_language": null,
    "upper_text_script": null,
    "upper_text_content": null,
    "scribe": null,
    "patron": null,
    "text_of_colophon": null,
    "geopolitical_context": "Ganzou Uyghur Kingdom Central Asia",
    "languages": [
      "Old Tibetan"
    ],
    "forms": [
      "Scroll"
    ],
    "materials": [
      "Paper"
    ]
  },
  {
    "id": 6,
    "manuscript": "Bakshali Manuscript",
    "terminus_post_quem": "885",
    "terminus_ante_quem": "993",
    "number_of_folios": 70,
    "dimension_width": "14.5",
    "dimension_height": "8.9",
    "script": "Brahmi/Sharada",
    "content": "Technical (Mathematical) ",
    "religious_affiliation": null,
    "current_location": "Bodleian Library",
    "shelfmark": "MS Sansk. d. 14",
    "findspot": "Bakshali (Peshawar, Pakistan)",
    "place_of_composition": null,
    "bibliography": "Augustus Hoernle, On the Bakshali Manuscript (Vienna, 1887); Kim Pfloker, Agathe Keller, Takao Hayashi, Clemency Montelle, and Dominik Wujastyk, \"The Bakhshālī Manuscript: A Response to the Bodleian Library’s Radiocarbon Dating,\" History of Science in South Asia 5 (2017): 134-150.",
    "scientific_analysis": null,
    "bilingual": null,
    "palimpsest": null,
    "colophon": "Y",
    "latitude": "34.008",
    "longitude": "71.5785",
    "printing": null,
    "entry_researcher": "Paul Dilley",
    "second_language": null,
    "second_script": null,
    "bilingual_format": null,
    "upper_text_language": null,
    "upper_text_script": null,
    "upper_text_content": null,
    "scribe": null,
    "patron": null,
    "text_of_colophon": null,
    "geopolitical_context": "Hindu Shahi Central Asia",
    "languages": [
      "Sanskrit"
    ],
    "forms": [
      "Scroll"
    ],
    "materials": [
      "Fragments"
    ]
  },
  {
    "id": 4,
    "manuscript": "Bower Manuscript",
    "terminus_post_quem": "300",
    "terminus_ante_quem": "600",
    "number_of_folios": 51,
    "dimension_width": null,
    "dimension_height": null,
    "script": "Brahmi",
    "content": "Technical (Medical)",
    "religious_affiliation": null,
    "current_location": "Bodleian Library, Oxford",
    "shelfmark": null,
    "findspot": "Kucha, Xinjiang, China (Taklamakan desert)",
    "place_of_composition": null,
    "bibliography": "August Friedrich Hoernle, The Bower Manuscript: Facsimile Leaves, Nagari Transcript, Romanised Transliteration and English Translation with Notes (Calcutta, 1910)",
    "scientific_analysis": null,
    "bilingual": null,
    "palimpsest": null,
    "colophon": null,
    "latitude": "41.716",
    "longitude": "82.966",
    "printing": null,
    "entry_researcher": "Paul Dilley",
    "second_language": null,
    "second_script": null,
    "bilingual_format": null,
    "upper_text_language": null,
    "upper_text_script": null,
    "upper_text_content": null,
    "scribe": null,
    "patron": null,
    "text_of_colophon": null,
    "geopolitical_context": "Kingdom of Kucha Central Asia",
    "languages": [
      "Sanskrit"
    ],
    "forms": [
      "Pothi"
    ],
    "materials": [
      "Birchbark"
    ]
  }
    ]
